[package]
name = "ozzy/staresatu"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1" 
# GoodSignal doesn't play well with Trove :(
# Signal = "stravant/goodsignal@0.2.1"
Component = "sleitnick/component@2.4.8"
Trove = "sleitnick/trove@1.4.0"
